alchemy/accounts/routes.py
from alchemy.accounts.forms import RegistrationForm,ResetPasswordForm,LoginForm,DeleteAccountForm,EditAccountForm,ResetPasswordForm,ProfilePictureForm
from flask import render_template,request,url_for,flash,get_flashed_messages,redirect
from flask_login import login_user,current_user,logout_user,login_required
from alchemy.utilities.models import Account,Phone,Email,Name,Signin
from alchemy.utils import error_log,error_string,get_date_string
from alchemy.utilities.exceptions import QueryException
from alchemy.accounts.utils import crop_to_square
from alchemy.utilities.database import Session
from alchemy import app
from flask import Blueprint
from io import BytesIO
from PIL import Image
import base64
import re


account = Blueprint('account',__name__,template_folder='templates',static_folder='static',static_url_path='/accounts/static')


@account.route('/register', methods=['GET','POST'])
def register_page():
    form = RegistrationForm()
    if form.validate_on_submit():
        with Session() as session:
            try:
                QueryException.clear_errors()
                year_entered = int(str(form.registration_age.data).split('-')[0])
                current_year = int(get_date_string(date_format='get_year'))
                if Account.unique_username(session,form.registration_username.data):
                    QueryException.add_error_message(f"The username {form.registration_username.data} is already in use.")

                if Email.unique_email(session,form.registration_email_address.data):
                    QueryException.add_error_message(f"The email {form.registration_email_address.data} is already in use.")

                if not re.match('^[0-9]{10}$',form.registration_phone_number.data):
                    QueryException.add_error_message(f"The phone number you entered is invalid.")
                elif Phone.unique_phone(session,form.registration_phone_number.data):
                    QueryException.add_error_message(f"The phone number {form.registration_phone_number.data} is already in use.")

                if Account.password_match(form.registration_password.data,form.registration_verify_password.data):
                    QueryException.add_error_message(f"The passwords do not match.")

                if current_year - year_entered < 0:
                    QueryException.add_error_message(f"Come back when your born.")
                elif  current_year - year_entered < 18:
                    QueryException.add_error_message(f"Your must be 18 or older to signup.")
                elif current_year - year_entered >= 135:
                    QueryException.add_error_message(f"You must be in the land of the living to signup.")

                if QueryException.error_count():
                    QueryException.show_error_messages()

            except QueryException:
                pass
            except Exception as e:
                if form.registration_age.data == None:
                    flash(f"The date you entered is invalid.",category="danger")
                else:
                    flash(f"{type(e).__name__}: {error_string(error=e)}",category="danger")
                error_log(error=e)
            else:

                new_user = {
                    'username':form.registration_username.data,
                    'password':form.registration_verify_password.data,
                    'first_name':(form.registration_first_name.data).title(),
                    'last_name':(form.registration_last_name.data).title(),
                    'email_address':form.registration_email_address.data,
                    'phone_number':form.registration_phone_number.data,
                    'age':form.registration_age.data,
                    'login':True
                }

                login_user(Signin.get_session(session).load_user(Account.create_account(**new_user)),remember=False)
                flash(f"{form.registration_username.data} was successfully created.",category='success')
                return redirect(url_for('market.market_page', username=current_user.username))

    return render_template('register.html',form=form)


@account.route('/login', methods=['GET','POST'])
def login_page():
    form=LoginForm()
    if form.validate_on_submit():
        with Session() as session:
            try:
                QueryException.clear_errors()
                attempted_user = session.query(Account).filter_by(username=form.login_username.data).first()
                if attempted_user and attempted_user.check_password_correction(form.login_password.data):
                    flash(f'Welcome back {(" ".join([attempted_user.name.first_name,attempted_user.name.last_name])).title()} (\'{form.login_username.data}\')', category='success')
                    get_user = Signin.get_session(session).load_user(attempted_user.id)
                    login_user(get_user,remember=form.login_remember_me.data)

                    return redirect(url_for('market.market_page', username=attempted_user.username))
                else:
                    QueryException.add_error_message(f"The username or password does not match.")
                if QueryException.error_count():
                    QueryException.show_error_messages()
            except QueryException:
                pass
            except Exception as e:
                flash(f"{type(e).__name__}: {error_string(error=e)}",category="danger")
                error_log(error=e)

    return render_template('login.html',messages=get_flashed_messages(),form=form)


@account.route('/logout')
def logout_page():
    flash("you logged out of your account", category='primary')
    logout_user()
    return redirect( url_for('main.home_page'))


@account.route('/<username>/settings', methods=['GET','POST'])
@login_required
def settings_page(username):
    delete_form=DeleteAccountForm()
    edit_form=EditAccountForm()
    password_form=ResetPasswordForm()
    image_form=ProfilePictureForm()

    edit_form.edit_first_name.data = edit_form.edit_first_name.data or current_user.name.first_name
    edit_form.edit_last_name.data = edit_form.edit_last_name.data or current_user.name.last_name
    edit_form.edit_email_address.data = edit_form.edit_email_address.data or current_user.email_address.email_address
    edit_form.edit_phone_number.data = edit_form.edit_phone_number.data or current_user.phone_number.phone_number

    if request.method == 'POST':
        with Session() as session:
            user = session.query(Account).get(current_user.id)
            if delete_form.submit_delete_account_form.data and request.form['form_name'] =='delete_form':
                if (delete_form.delete_username.data).strip() == current_user.username:
                    session.delete(session.query(Account).get(current_user.id))
                    session.commit()
                    return redirect(url_for('account.logout_page'))
                else:
                    flash(f"input box did not match your username, account was not deleted", category='warning')

            if edit_form.submit_edit_account_form.data and request.form['form_name'] == 'edit_form':
                try:
                    QueryException.clear_errors()

                    if Email.unique_email(session,edit_form.edit_email_address.data) and edit_form.edit_email_address.data != current_user.email_address.email_address:
                        QueryException.add_error_message(f"The email {edit_form.edit_email_address.data} is already in use.")

                    if not re.match('^[0-9]{10}$',edit_form.edit_phone_number.data):
                        QueryException.add_error_message(f"The phone number you entered is invalid.")
                    elif Phone.unique_phone(session,edit_form.edit_phone_number.data) and edit_form.edit_phone_number.data != current_user.phone_number.phone_number:
                        QueryException.add_error_message(f"The phone number {edit_form.edit_phone_number.data} is already in use.")

                    if QueryException.error_count():
                        QueryException.show_error_messages()

                except QueryException:
                    pass
                except Exception as e:
                    flash(f"{type(e).__name__}: {error_string(error=e)}",category="danger")
                    error_log(error=e)
                else:
                    message_template = "You have successfully updated your {} from {} to {}!"
                    name = session.query(Name).get(current_user.id)
                    if edit_form.edit_first_name.data != current_user.name.first_name:
                        name.first_name = (edit_form.edit_first_name.data).title()
                        flash(message_template.format('first name',current_user.name.first_name,edit_form.edit_first_name.data), category='success')
                        current_user.name.first_name = edit_form.edit_first_name.data

                    if edit_form.edit_last_name.data != current_user.name.last_name:
                        name.last_name = (edit_form.edit_last_name.data).title()
                        flash(message_template.format('last name',current_user.name.last_name,edit_form.edit_last_name.data), category='success')
                        current_user.name.last_name = edit_form.edit_last_name.data

                    if edit_form.edit_email_address.data != current_user.email_address.email_address:
                        email = session.query(Email).get(current_user.id)
                        email.email_address = edit_form.edit_email_address.data
                        flash(message_template.format('email address',current_user.email_address.email_address,edit_form.edit_email_address.data), category='success')
                        current_user.email_address.email_address = edit_form.edit_email_address.data

                    if edit_form.edit_phone_number.data != current_user.phone_number.phone_number:

alchemy/main/routes.py
from flask import render_template
from flask import Blueprint


main = Blueprint('main',__name__,template_folder='templates',static_folder='static',static_url_path='/main/static')


@main.route('/')
@main.route('/home')
def home_page():
    return render_template('home.html')

alchemy/market/routes.py
from alchemy.market.forms import SellItemForm,PurchaseItemForm,AddCommentForm
from flask import render_template,request,flash,get_flashed_messages
from alchemy.utilities.models import Item,Wallet,Comment,Purchase
from flask_login import current_user,login_required
from alchemy.utilities.database import Session
from sqlalchemy.orm.exc import NoResultFound
from alchemy.utils import error_log
from flask import Blueprint
from decimal import Decimal
import json


market = Blueprint('market',__name__,template_folder='templates',static_folder='static',static_url_path='/market/static')

@market.route('/<username>/market', methods=['GET','POST'])
@login_required
def market_page(username):
    purchase_form= PurchaseItemForm()
    sell_form = SellItemForm()
    with Session() as session:
        purchased_items = session.query(Item).filter(Item.stock > 0)
        owned_items = session.query(Purchase).filter_by(owner=current_user.id)
        if request.method == 'POST':
            funds = session.query(Wallet).get(current_user.id)
            if request.form['form_name'] == 'purchase_form':
                purchased_json_item = json.loads(request.form.get("unowned_item"))
                purchased_item = session.query(Item).get(int(purchased_json_item['id']))
                item_count = int(request.form['purchase_count'])
                cost = Decimal(Decimal(purchased_json_item["price"]) * item_count).quantize(Decimal('0.01'))
                if funds.balance - cost > 0:
                    purchased_item.stock -= item_count
                    funds.balance -= cost
                    try:
                        add_item = session.query(Purchase).filter_by(owner=current_user.id).filter_by(barcode=purchased_json_item["barcode"]).one()
                        add_item.count += item_count
                    except NoResultFound:
                        purchasing = Purchase(owner=current_user.id,count=item_count,barcode=purchased_json_item["barcode"])
                        session.add(purchasing)
                    flash(f'You successfully purchased the { purchased_json_item["name"] }.', category="success")
                    session.commit()
                else:
                    flash("insufficient funds", category="danger")

            elif request.form['form_name'] == 'sold_form':
                sold_json_item = json.loads(request.form.get("sold_item"))
                sold_item = session.query(Item).get(int(sold_json_item['id']))
                item_count = int(request.form['sell_count'])
                sold_item.stock += item_count
                funds.balance += Decimal(Decimal(sold_json_item["price"]) * item_count).quantize(Decimal('0.01'))
                try:
                    remove_item = session.query(Purchase).filter_by(owner=current_user.id).filter_by(barcode=sold_json_item["barcode"]).first()
                    remove_item.count -= item_count
                    result = session.query(Purchase).filter_by(owner=current_user.id).filter_by(barcode=sold_item.barcode).filter_by(count=0).delete()

                    if result:
                        flash(f"You sold out of your { sold_item.name }.", category="success")
                    else:
                        flash(f"You successfully sold { item_count } { sold_item.name }.", category="success")
                except Exception as e:
                    error_log(error=e)
                session.commit()

    current_user.balance.balance = session.query(Wallet.balance).filter_by(id=current_user.id).scalar()
    return render_template('market.html',messages=get_flashed_messages(),purchased_items=purchased_items,owned_items=owned_items,purchase_form=purchase_form,sell_form=sell_form)


@market.route('/<item>/comment', methods=['GET','POST'])
@login_required
def comments_page(item):
    form=AddCommentForm()
    with Session() as session:
        item = session.query(Item).filter_by(barcode=item).scalar()
        item_comments = session.query(Comment).filter_by(barcode=item.barcode)
        stars_count = {}
        stars_count['one'] = (item_comments.filter_by(rating=1)).count() or 0
        stars_count['two'] = (item_comments.filter_by(rating=2)).count() or 0
        stars_count['three'] = (item_comments.filter_by(rating=3)).count() or 0
        stars_count['four'] = (item_comments.filter_by(rating=4)).count() or 0
        stars_count['five'] = (item_comments.filter_by(rating=5)).count() or 0
        stars_count['total'] = stars_count['one'] + stars_count['two']  + stars_count['three']  + stars_count['four'] + stars_count['five']

        if form.validate_on_submit():
            itemRating = int(request.form['rating']) or 0
            if itemRating == 0 or form.title.data == None or form.content.data == None:
                flash('please give us a rating',category='danger')
            else:
                if request.method == "POST":
                    flash(f'{itemRating}',category='danger')

                    comment = Comment(barcode=item.barcode,written_by=current_user.username,title=form.title.data,body=form.content.data,rating=itemRating)
                    session.add(comment)

                    session.commit()
                    stars_count['one'] = (item_comments.filter_by(rating=1)).count() or 0
                    stars_count['two'] = (item_comments.filter_by(rating=2)).count() or 0
                    stars_count['three'] = (item_comments.filter_by(rating=3)).count() or 0
                    stars_count['four'] = (item_comments.filter_by(rating=4)).count() or 0
                    stars_count['five'] = (item_comments.filter_by(rating=5)).count() or 0
                    stars_count['total'] = stars_count['one'] + stars_count['two']  + stars_count['three']  + stars_count['four'] + stars_count['five']


        return render_template('posts.html',form=form,item=item,item_comments=item_comments,stars_count=stars_count)

alchemy/sandbox/routes.py
from flask import render_template,request,url_for,flash,redirect,current_app
from flask import render_template,request,flash,get_flashed_messages
from flask_login import current_user,login_required
from alchemy.utilities.database import Session
from alchemy.utils import error_log
from alchemy.sandbox.forms import FormValidationForm
from flask import Blueprint
import json


sandbox = Blueprint('sandbox',__name__,template_folder='templates',static_folder='static',static_url_path='/sandbox/static')

@sandbox.route('/<username>/sandbox/forms', methods=['GET','POST'])
@login_required
def form_validation_page(username):
    if current_user.groups.user_group == 'root_users':
        form=FormValidationForm()
        if request.method == "POST":
            form_data =  form.inputbox.data
            print(form_data)
            flash(f"{form_data}",category="success")
        return render_template('form_validation.html',form=form)
    else:
        return redirect(url_for('main.home_page'))

alchemy/templates/_base.html
{% from "_macros.html" import add_margin  %}
{% from "_macros.html" import add_icon  %}
{% from "_macros.html" import errors  %}
{% from "_macros.html" import spacer  %}
{% from "_macros.html" import modal  %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="icon" type="image/png" href="https://icons.iconarchive.com/icons/pauloruberto/custom-round-yosemite/512/Python-icon.png">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Varela+Round">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/_base.css') }}">
        {% block stylesheets %}{% endblock %}
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body class="bg-black">
        <nav id="navigationBar" class="navbar sticky-top navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
            <div class="container-fluid">
                {% if current_user.is_authenticated %}
                    <a class="navbar-brand" href="{{ url_for('account.settings_page',username=current_user.username) }}"><img id='Profile_picutre' width='24px' hight='24px' src="{{ current_user.profile_picture }}" alt="..." width='64px' hight='64px' class="rounded-circle border border-white">{{ add_margin(1) }}{{current_user.username}}</a>{{ add_margin(3) }}
                {% else %}
                    <a class="navbar-brand" href="{{ url_for('main.home_page') }}">{{ add_icon(classes='fa-house-chimney') }}Home</a>
                {% endif %}
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        {% if current_user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('main.home_page') }}">{{ add_icon(classes='fa-house-chimney') }}Home</a>
                            </li>
                        {% endif %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="accountDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ add_icon(classes=' fa-user') }}Account</a>
                            <div class="dropdown-menu bg-dark" aria-labelledby="accountDropdown">
                                {% if current_user.is_authenticated %}
                                    <a class="dropdown-item" href="{{ url_for('account.logout_page') }}">{{ add_icon(classes='fa-right-to-bracket fa-rotate-180') }}Logout<span class="sr-only">(current)</span></a>
                                {% else %}
                                    <a class="dropdown-item" href="{{ url_for('account.login_page') }}">{{ add_icon(classes='fa-right-to-bracket') }}Login<span class="sr-only">(current)</span></a>
                                    <a class="dropdown-item" href="{{ url_for('account.register_page') }}">{{ add_icon(classes='fa-address-card') }}Register<span class="sr-only">(current)</span></a>
                                {% endif %}
                            </div>
                        </li>
                        {% if current_user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('market.market_page',username=current_user.username) }}">{{ add_icon(classes='fa-store') }}Market</a>
                            </li>
                            {% if current_user.groups.user_group == 'root_users' %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ url_for('administration.inspector_page',username=current_user.username) }}">{{ add_icon(classes='fa-sliders') }}Inspector</a>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="sandboxDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ add_icon(classes='fa-folder-open') }}Sandbox</a>
                                    <div class="dropdown-menu bg-dark" aria-labelledby="sandboxDropdown">
                                        <a class="dropdown-item" href="{{ url_for('sandbox.form_validation_page',username=current_user.username) }}">{{ add_icon(classes='fa-check') }}Validation Forms<span class="sr-only">(current)</span></a>
                                    </div>
                                </li>
                            {% endif %}
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="informationDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ add_icon(classes='fa-circle-info') }}Information</a>
                                    <div class="dropdown-menu bg-dark" aria-labelledby="informationDropdown">
                                        {% if current_user.groups.user_group in ['root_users','privilaged_users'] %}
                                            <a class="dropdown-item" href="{{ url_for('information.version_page') }}">{{ add_icon(classes='fa-code-branch') }}Version Info<span class="sr-only">(current)</span></a>
                                            {% if current_user.groups.user_group == 'root_users' %}
                                                <a class="dropdown-item" href="{{ url_for('information.cascading_style_sheets_info_page') }}">{{ add_icon(classes='fa-brands fa-css3') }}Cascading Style Sheets<span class="sr-only">(current)</span></a>
                                            {% endif %}
                                        {% endif %}
                                        <a class="dropdown-item" href="{{ url_for('information.sql_setup_page') }}">{{ add_icon(classes='fa-brands fa-python') }}SQL Setup with Python<span class="sr-only">(current)</span></a>
                                        <a class="dropdown-item" href="{{ url_for('information.presentation_page') }}">{{ add_icon(classes='fa-person-chalkboard') }}Presentation<span class="sr-only">(current)</span></a>
                                    </div>
                                </li>

                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <div id="paddingDiv" class="bgc container-fluid d-flex flex-column pt-3">
            <div class="d-flex flex-column bgc" id="content">{% block content %}{% endblock %}{{ spacer(1) }}</div>
        </div>
        <footer id="footerBar" class="footer fgc py-3 bg-black text-center text-white-50">
                </section>
                    <div class="social d-flex justify-content-center pt-3">
                        <a href="https://github.com/Canine-Table/Flask-SQL-Alchemy"><i class="fa fa-brands fa-github"></i></a>
                    </div>{{ spacer(1) }}
                </section>
                <div class="container px-4 px-lg-5">Copyright &copy; Quality Queries 2023</div>
        </footer>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
        <script src="{{ url_for('static', filename='js/_base.js')}}"></script>
    </body>
</html>

alchemy/templates/_errors.html
{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for catagory, message in messages %}
            <div class="alert alert-{{ catagory }}" role="alert">
                <button type="button" class="m1-2 mb-1 close" data-dismiss="alert" aria-label="close">
                    <span aria-hidden="true" >&times;</span>
                </button>
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}