alchemy/market/forms.py
from wtforms import StringField,SubmitField,TextAreaField,HiddenField,IntegerField
from wtforms.validators import Length,DataRequired,InputRequired,NumberRange
from wtforms.widgets.core import NumberInput
from flask_wtf import FlaskForm

class PurchaseItemForm(FlaskForm):
    purchase_count = IntegerField(default="1",render_kw={"class":"btn-secondary col-12","data-bs-theme":'dark'},name="purchase_count",widget=NumberInput(step=1, min=1))
    submit_purchase_item_form = SubmitField(label='Purchase',render_kw={'class':'btn btn-success'},id='PurchaseItemForm')

class SellItemForm(FlaskForm):
    sell_count = IntegerField(default="1",render_kw={"class":"btn-secondary col-12","data-bs-theme":'dark'},name="sell_count",widget=NumberInput(step=1, min=1))
    submit_sell_item_form = SubmitField(label="Sell",id='SellItemForm',render_kw={'class':'btn btn-danger'})

class AddItemForm(FlaskForm):
    submit_add_item_form = SubmitField(label="Add Item",id='AddItemForm',render_kw={'class':'btn btn-success'})


class RemoveItemForm(FlaskForm):
    submit_remove_item_Form = SubmitField(label="Remove Item",id='RemoveItemForm',render_kw={'class':'btn btn-danger'})

class AddCommentForm(FlaskForm):
    title = StringField(label='Title',validators=[DataRequired(),Length(max=128, message="Message title must be between 0 and 128, please provide a shorter title for your post.")])
    content = TextAreaField(label='Content',validators=[DataRequired(),Length(max=16383, message="Message body must be between 0 and 16383 characters, please post a shortener message.")])
    rating = HiddenField(label='star_rating', validators=[DataRequired(), NumberRange(min=1, max=5),InputRequired(message="Please give us a rating between %(min)d and %(max)d before you submit your comment.")])
    submit_add_comment_form = SubmitField(label="Post Comment",id='AddCommentForm',render_kw={'class':'btn btn-primary'})

alchemy/market/routes.py
from alchemy.market.forms import SellItemForm,PurchaseItemForm,AddCommentForm
from flask import render_template,request,flash,get_flashed_messages
from alchemy.utilities.models import Item,Wallet,Comment,Purchase
from flask_login import current_user,login_required
from alchemy.utilities.database import Session
from sqlalchemy.orm.exc import NoResultFound
from alchemy.utils import error_log
from flask import Blueprint
from decimal import Decimal
import json


market = Blueprint('market',__name__,template_folder='templates',static_folder='static',static_url_path='/market/static')

@market.route('/<username>/market', methods=['GET','POST'])
@login_required
def market_page(username):
    purchase_form= PurchaseItemForm()
    sell_form = SellItemForm()
    with Session() as session:
        purchased_items = session.query(Item).filter(Item.stock > 0)
        owned_items = session.query(Purchase).filter_by(owner=current_user.id)
        if request.method == 'POST':
            funds = session.query(Wallet).get(current_user.id)
            if request.form['form_name'] == 'purchase_form':
                purchased_json_item = json.loads(request.form.get("unowned_item"))
                purchased_item = session.query(Item).get(int(purchased_json_item['id']))
                item_count = int(request.form['purchase_count'])
                cost = Decimal(Decimal(purchased_json_item["price"]) * item_count).quantize(Decimal('0.01'))
                if funds.balance - cost > 0:
                    purchased_item.stock -= item_count
                    funds.balance -= cost
                    try:
                        add_item = session.query(Purchase).filter_by(owner=current_user.id).filter_by(barcode=purchased_json_item["barcode"]).one()
                        add_item.count += item_count
                    except NoResultFound:
                        purchasing = Purchase(owner=current_user.id,count=item_count,barcode=purchased_json_item["barcode"])
                        session.add(purchasing)
                    flash(f'You successfully purchased the { purchased_json_item["name"] }.', category="success")
                    session.commit()
                else:
                    flash("insufficient funds", category="danger")

            elif request.form['form_name'] == 'sold_form':
                sold_json_item = json.loads(request.form.get("sold_item"))
                sold_item = session.query(Item).get(int(sold_json_item['id']))
                item_count = int(request.form['sell_count'])
                sold_item.stock += item_count
                funds.balance += Decimal(Decimal(sold_json_item["price"]) * item_count).quantize(Decimal('0.01'))
                try:
                    remove_item = session.query(Purchase).filter_by(owner=current_user.id).filter_by(barcode=sold_json_item["barcode"]).first()
                    remove_item.count -= item_count
                    result = session.query(Purchase).filter_by(owner=current_user.id).filter_by(barcode=sold_item.barcode).filter_by(count=0).delete()

                    if result:
                        flash(f"You sold out of your { sold_item.name }.", category="success")
                    else:
                        flash(f"You successfully sold { item_count } { sold_item.name }.", category="success")
                except Exception as e:
                    error_log(error=e)
                session.commit()

    current_user.balance.balance = session.query(Wallet.balance).filter_by(id=current_user.id).scalar()
    return render_template('market.html',messages=get_flashed_messages(),purchased_items=purchased_items,owned_items=owned_items,purchase_form=purchase_form,sell_form=sell_form)


@market.route('/<item>/comment', methods=['GET','POST'])
@login_required
def comments_page(item):
    form=AddCommentForm()
    with Session() as session:
        item = session.query(Item).filter_by(barcode=item).scalar()
        item_comments = session.query(Comment).filter_by(barcode=item.barcode)
        stars_count = {}
        stars_count['one'] = (item_comments.filter_by(rating=1)).count() or 0
        stars_count['two'] = (item_comments.filter_by(rating=2)).count() or 0
        stars_count['three'] = (item_comments.filter_by(rating=3)).count() or 0
        stars_count['four'] = (item_comments.filter_by(rating=4)).count() or 0
        stars_count['five'] = (item_comments.filter_by(rating=5)).count() or 0
        stars_count['total'] = stars_count['one'] + stars_count['two']  + stars_count['three']  + stars_count['four'] + stars_count['five']

        if form.validate_on_submit():
            itemRating = int(request.form['rating']) or 0
            if itemRating == 0 or form.title.data == None or form.content.data == None:
                flash('please give us a rating',category='danger')
            else:
                if request.method == "POST":
                    flash(f'{itemRating}',category='danger')

                    comment = Comment(barcode=item.barcode,written_by=current_user.username,title=form.title.data,body=form.content.data,rating=itemRating)
                    session.add(comment)

                    session.commit()
                    stars_count['one'] = (item_comments.filter_by(rating=1)).count() or 0
                    stars_count['two'] = (item_comments.filter_by(rating=2)).count() or 0
                    stars_count['three'] = (item_comments.filter_by(rating=3)).count() or 0
                    stars_count['four'] = (item_comments.filter_by(rating=4)).count() or 0
                    stars_count['five'] = (item_comments.filter_by(rating=5)).count() or 0
                    stars_count['total'] = stars_count['one'] + stars_count['two']  + stars_count['three']  + stars_count['four'] + stars_count['five']


        return render_template('posts.html',form=form,item=item,item_comments=item_comments,stars_count=stars_count)

alchemy/market/templates/market.html
{% extends '_base.html' %}
{% block title %}Market{% endblock %}
{% block content %}
    <div class="container-fluid rounded jumbotron p-2 my-3 text-center jbtron">
        <div class="jumbotron fgc rounded p-3 my-2 {{ 'mb-4' if get_flashed_messages() }}">
            <h1>Hello {{ current_user.username }}, welcome to the Flask Marketplace.</h1>{{ spacer(1) }}
        </div>
        {{ errors() }}
    </div>
    <div class="jumbotron rounded container-fluid p-2 my-3 jbtron">
        <div class="jumbotron rounded bgc p-3 my-2">
            <div class="jumbotron rounded fgc p-3 my-2 {{ 'mb-4' if owned_items.count() > 0 }}">
                <h2>Owned Items</h2>
                <p>{% if owned_items.count() > 0 %}Click on sell item to put the item back on the market.{% else %}You currently have no items.{% endif %}</p>{{ spacer(1) }}
            </div>
            <div class="col">
                <div class="row">
                    {% for owned_item in owned_items %}
                        <div class="col-md-4" >
                            <div class="card text-center mb-4 bkg">
                                <div class="card-body my_content">
                                    <h5 class="card-title"><b><u>{{ owned_item.item_purchase.name }}</b></u></h5>
                                    {% macro sell_modal_body() %}
                                        <form method="POST" onsubmit="submit_sell_item_form.disabled=true;loadForm(this,'SellItemForm');">
                                            {{ sell_form.hidden_tag() }}
                                            <p class="text-left">Are you sure you want to sell your <b>{{ owned_item.item_purchase.name }}</b> for <b>${{ owned_item.item_purchase.price }}</b>?</p>
                                            {% set sold_item_counter = "sold_item_count-" + owned_item.barcode %}
                                            {{ sell_form.sell_count(max=owned_item.count) }}
                                    {% endmacro %}
                                    {% macro sell_modal_footer() %}
                                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                            <input id="form_name-{{ owned_item.id }}" name="form_name" type="hidden" value="sold_form">
                                            <input id="sold_item-{{ owned_item.id }}" name="sold_item" type="hidden" value='{{ {"id":owned_item.item_purchase.id,"name":owned_item.item_purchase.name,"price":int(owned_item.item_purchase.price),"barcode":owned_item.barcode,"description":owned_item.item_purchase.description,"stock":owned_item.count,"count":owned_item.owner} | tojson }}'>
                                            {{ sell_form.submit_sell_item_form }}
                                        </form>
                                    {% endmacro %}
                                    {% set mid = secrets.token_hex(12)|upper %}
                                    <p class="card-text"><strong>This item costs ${{ owned_item.item_purchase.price }} {% if owned_item.count > 1 %}each{% endif %}</strong></p>
                                    <button type="button" class="btn btn-outline btn-danger btn-block mb-3" data-bs-toggle="modal" data-bs-target="#Modal-{{ mid }}">Sell {{ owned_item.item_purchase.name }}</button>
                                    <p class="card-text">You have <b>{{ owned_item.count }}</b> {{ owned_item.item_purchase.name }} {% if owned_item.count > 1 %}items{% else %}item{% endif %}</p>
                                    {{ modal(
                                        modal_id=mid,
                                        button_id=mid,
                                        modal_title=add_icon('fa-money-bill',words_end=owned_item.item_purchase.name),
                                        modal_header=True,
                                        modal_body=True,
                                        modal_footer=True,
                                        body=sell_modal_body(),
                                        body_classes='text-left',
                                        footer=sell_modal_footer(),
                                        in_button=False,
                                        keep_close=False
                                    ) }}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <div class="jumbotron rounded p-2 my-3 container-fluid bgc">
        <div class="jumbotron rounded p-2 jbtron">
            <div class="jumbotron rounded fgc p-3 my-2 {{ 'mb-4' if purchased_items.count() > 0 }}">
                <h2>Available Items on the Market</h2>
                <p>{% if purchased_items.count() > 0 %}Click on one of the items to start buying.{% else %}The marketplace is currently out of stock.{% endif %}</p>{{ spacer(1) }}
            </div>
            <div class="overflow-auto">
                {% if purchased_items.count() > 0 %}
                    <table class="table table-hover table-bordered table-dark">
                        <thead>
                            <tr>
                                <th scope="col">Name</th>
                                <th scope="col">Price</th>
                                <th scope="col">Stock</th>
                                <th scope="col">Options</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for purchased_item in purchased_items %}
                                <tr>
                                    <td>{{ purchased_item.name }}</td>
                                    <td>${{ purchased_item.price }}</td>
                                    <td>{{ purchased_item.stock }}</td>
                                    <td>
                                        <a class="btn btn-primary my-1" href="{{ url_for('market.comments_page',item=purchased_item.barcode) }}">Comment</a>
                                        {% macro info_body() %}
                                            <p><b>Item ID:</b> {{ purchased_item.id }}</p>
                                            <p><b>Stock:</b> {{ purchased_item.stock }}</p>
                                            <p><b>Price:</b> ${{ purchased_item.price }}</p>
                                            <p><b>Description:</b> {{ purchased_item.description }}</p>
                                            <p><b>Date Added:</b> {{ purchased_item.date_added }}</p>
                                            {% if purchased_item.last_updated %}
                                                <p><b>Last Updated:</b> {{ purchased_item.last_updated }}</p>
                                            {% endif %}
                                        {% endmacro %}
                                        {{ modal(
                                            modal_id=secrets.token_hex(12)|upper,
                                            button_classes='btn-outline btn-info my-1',
                                            button_text='More Info',
                                            modal_header=True,
                                            modal_body=True,
                                            modal_footer=True,
                                            modal_title=add_icon(classes='fa-circle-info',words_end=purchased_item.name),
                                            body=info_body(),
                                        ) }}
                                        {% macro purchase_body() %}
                                            <form method="POST" onsubmit="submit_purchase_item_form.disabled=true;loadForm(this,'PurchaseItemForm');">
                                                {{ purchase_form.hidden_tag() }}
                                                <p>Are you sure you want to buy a <b>{{ purchased_item.name }}</b> for <b>${{ purchased_item.price }}</b>?</p>
                                                {{ purchase_form.purchase_count(max=purchased_item.stock) }}
                                        {% endmacro %}
                                        {% macro purchase_footer() %}
                                                <input id="purchase_form_name-{{ purchased_item.id }}" name="form_name" type="hidden" value="purchase_form">
                                                <input id="unowned_item-{{ purchased_item.id }}" name="unowned_item" type="hidden" value='{{ {"id":purchased_item.id,"name":purchased_item.name,"price":int(purchased_item.price),"barcode":purchased_item.barcode,"description":purchased_item.description,"stock":purchased_item.stock} | tojson }}'>
                                                {{ purchase_form.submit_purchase_item_form }}
                                            </form>
                                        {% endmacro %}
                                        {{ modal(
                                            modal_id=secrets.token_hex(12)|upper,
                                            button_classes='btn-outline btn-success my-1',
                                            button_text='Purchase',
                                            modal_header=True,
                                            modal_body=True,
                                            modal_footer=True,
                                            modal_title=add_icon('fa-cart-shopping',words_end=purchased_item.name),
                                            body=purchase_body(),
                                            footer=purchase_footer()
                                        ) }}
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <div class="jumbotron fgc p-3 mb-2">
                        <h5 class="text-center"><b>Sorry but the store is currently out of stock</b></h5>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
    <script src="{{ url_for('market.static', filename='js/_market.js')}}"></script>
{% endblock %}

alchemy/market/templates/posts.html
{% extends '_base.html' %}
{% block title %}Comments{% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" href="{{ url_for('market.static', filename='css/_posts.css') }}">

{% endblock %}
{% block content %}
    <div class="container-fluid jumbotron rounded p-2 text-center jbtron">
        <div class="jumbotron rounded fgc p-3 mt-3">
            <h1>{{ item.name }} Reviews</h1>{{ spacer(1) }}
            {{ errors() }}

            <div class="row my-3">
                <div class="side">
                    <div>5 star</div>
                </div>
                <div class="middle">
                    <div class="bar-container">
                    <div class="bar-5"></div>
                    </div>
                </div>
                <div class="side right">
                    <div>{{ stars_count['five'] }}</div>
                </div>
                <div class="side">
                    <div>4 star</div>
                </div>
                <div class="middle">
                    <div class="bar-container">
                    <div class="bar-4"></div>
                    </div>
                </div>
                <div class="side right">
                    <div>{{ stars_count['four'] }}</div>
                </div>
                <div class="side">
                    <div>3 star</div>
                </div>
                <div class="middle">
                    <div class="bar-container">
                    <div class="bar-3"></div>
                    </div>
                </div>
                <div class="side right">
                    <div>{{ stars_count['three'] }}</div>
                </div>
                <div class="side">
                    <div>2 star</div>
                </div>
                <div class="middle">
                    <div class="bar-container">
                    <div class="bar-2"></div>
                    </div>
                </div>
                <div class="side right">
                    <div>{{ stars_count['two'] }}</div>
                </div>
                <div class="side">
                    <div>1 star</div>
                </div>
                <div class="middle">
                    <div class="bar-container">
                    <div class="bar-1"></div>
                    </div>
                </div>
                <div class="side right">
                    <div>{{ stars_count['one'] }}</div>
                </div>
            </div>
            <form method="POST" onsubmit="submit.disabled=true;loadForm(this);">
                {{ form.hidden_tag() }}

                {% macro post_body() %}
                    <div id="starRating">
                        <span id="1" class="fa fa-star"></span>
                        <span id="2" class="fa fa-star"></span>
                        <span id="3" class="fa fa-star"></span>
                        <span id="4" class="fa fa-star"></span>
                        <span id="5" class="fa fa-star"></span>
                    </div>
                    {{ form.title(class="col-12 jbtron my-2", placeholder='comment title') }}
                    {{ form.content(class="col-12 p-2 jbtron my-2", placeholder='comment body') }}
                {% endmacro %}

                {% macro post_footer() %}
                    {{ form.submit }}
                {% endmacro %}

                {{ modal(
                    modal_id=secrets.token_hex(12)|upper,
                    button_classes='col-12 my-3 btn-outline-info',
                    button_text='New Comment',
                    modal_title='Add Comment',
                    button_id=secrets.token_hex(12)|upper,
                    modal_header=True,
                    modal_body=True,
                    modal_footer=True,
                    body=post_body(),
                    footer=post_footer(),
                ) }}
            </form>
        </div>

    </div>{{ spacer(1) }}
    {% if item_comments.count() > 0 %}
        {% for item_comment in item_comments %}
            <div class="card" data-bs-theme='dark'>
                {% set mid = secrets.token_hex(32) %}
                <div class="card-header text-white fgc">{{ item_comment.title }}</div>
                <div class="card-body bg-dark text-white"><p class="card-text">{{ item_comment.body }}</p></div>
                <div class="card-footer p-0 m-0 mb-1 accordion accordion-flush" id="{{ mid }}">
                    <div class="accordion-item">
                        <h2 class="accordion-header">
                            <button class="fgc text-white accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse-{{ mid }}" aria-expanded="false" aria-controls="flush-collapse-{{ mid }}">@ {{ item_comment.written_by }}</button>
                        </h2>
                        <div id="flush-collapse-{{ mid }}" class="accordion-collapse collapse" data-bs-parent="#{{ mid }}">
                            <div class="bg-dark accordion-body">
                                <p><b><i>Creation Date:</i></b>&nbsp;{{ item_comment.creation_date }}</p>
                                {% if  item_comment.last_updated %}
                                    <p><b><i>Last Updated::</i></b>&nbsp;{{ item_comment.last_updated }}</p>
                                {% endif %}
                                <button class='btn my-3 btn-outline-info'>Comment</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>{{ spacer(2) }}
        {% endfor %}
    {% else %}
        <div class="container-fluid jumbotron rounded p-2 text-center jbtron">
            <div class="jumbotron fgc p-3 mb-2 rounded">
                <h5 class="text-center"><b>This item has no comments.</b></h5>
            </div>
        </div>
    {% endif %}
    <script src="{{ url_for('market.static', filename='js/_posts.js')}}"></script>
{% endblock %}