alchemy/information/forms.py
from wtforms import SearchField,SubmitField
from wtforms.validators import DataRequired,Regexp
from flask_wtf import FlaskForm

class SearchModule(FlaskForm):
    search = SearchField(validators=[Regexp(r"\w+(-\w+)?")])
    submit = SubmitField(label="Search")

alchemy/information/routes.py
from flask import render_template,request,url_for,flash,redirect,current_app
from alchemy.information.utils import filter_results,n_to_br
from flask_login import current_user,login_required
from alchemy.information.forms import SearchModule
from flask import render_template
from flask import Blueprint
import subprocess
import json


information = Blueprint('information',__name__,template_folder='templates',static_folder='static',static_url_path='/information/static')


@information.route('/information/modules/versions',methods=['GET','POST'])
@login_required
def version_page():
    if current_user.groups.user_group in ['root_users','privilaged_users']:
        form=SearchModule()
        pip3_modules = {}
        pip3_modules['load'] = None
        pip3_modules['TypeNone'] = False
        pip3_modules['names_n_versions'] = json.loads(subprocess.check_output(["pip", "list","--format","json"]).decode())
        pip3_modules['names'] = [modules['name'] for modules in pip3_modules['names_n_versions']]
        if request.method == 'POST':
            if request.form['get_more_info']:
                pip3_modules['load'] = request.form['get_more_info']
            else:
                pip3_modules['load'] = None

            pip3_modules['names_n_versions'] = json.loads(subprocess.check_output(["pip", "list","--format","json"]).decode())
            filter_result = filter_results(form.search.data,pip3_modules['names'])
            if filter_result == None:
                pip3_modules['TypeNone'] = True
            else:
                pip3_modules['names'] = filter_result
            if pip3_modules['load'] != 'None':
                return redirect(url_for('information.module_info_page',module_name=pip3_modules['load']))
        return render_template('versions.html',form=form,pip3_modules=pip3_modules)
    else:
        return redirect(url_for('main.home_page'))


@information.route('/information/presentation',methods=['GET'])
@login_required
def presentation_page():
    return render_template('presentation.html')


@information.route('/information/modules/<module_name>',methods=['GET'])
@login_required
def module_info_page(module_name):
    if current_user.groups.user_group in ['root_users','privilaged_users']:
        get_module_info = subprocess.check_output(["pip", "show",f"{module_name}"]).decode()
        module_info = n_to_br(get_module_info)

        return render_template('module_information.html',module_name=module_name,module_info=module_info)
    else:
        return redirect(url_for('main.home_page'))


@information.route('/information/css',methods=['GET'])
@login_required
def cascading_style_sheets_info_page():
    if current_user.groups.user_group == 'root_users':
        return render_template('cascading_style_sheets.html')
    else:
        return redirect(url_for('main.home_page'))

@information.route('/information/sql/setup',methods=['GET'])
@login_required
def sql_setup_page():
    return render_template('sql_setup.html')

alchemy/information/templates/cascading_style_sheets.html
{% extends '_base.html' %}
{% block title %}CSS{% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" href="{{ url_for('information.static', filename='css/_cascading_style_sheets.css') }}">
{% endblock %}
{% block content %}
    <div class="container-fluid jumbotron rounded p-2 ml-4 mr-4 text-center jbtron">
    </div>
    <script src="{{ url_for('information.static', filename='js/_cascading_style_sheets.js')}}"></script>
{% endblock %}

alchemy/information/templates/module_information.html
{% extends '_base.html' %}
{% block title %}{{ module_info }} Info{% endblock %}
{% block content %}
    <div class="container-fluid rounded jumbotron p-2 my-3 jbtron">
        <div class="jumbotron bgc rounded p-3 my-2">
            <div class="jumbotron fgc rounded px-4 pb-4 pt-4 mt-1 mb-0">
                <h1 class='text-center'><b><i>{{ module_name }}</i></b></h1>
            </div>
            <div class="jumbotron rounded fgc mt-4 px-4 pb-4 pt-5 my-1 mb-2">
                <h5>{{ module_info|safe }}</h5>
            </div>
            <a class='text-center col-12 btn-secondary btn mt-3' href="{{ url_for('information.version_page') }}">Back</a>
        </div>
    </div>
{% endblock %}

alchemy/information/templates/presentation.html
{% extends '_base.html' %}
{% block title %}Presentation{% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" href="{{ url_for('information.static', filename='css/_presentation.css') }}">
{% endblock %}
{% block content %}
    <div class="container-fluid jumbotron p-2 my-3 text-center rounded jbtron">
        <div class="jumbotron fgc rounded p-3 my-2">
            <h1>Quality Queries</h1>
            <h3>Christopher Asante, Yunhai Yang, Pablo Bazaes, Benjamin Wilson</h3>
        </div>
    </div>
    <div id="qualityQueriesCarouselContainer" class="jbtron rounded d-flex ">
        <div id="qualityQueriesCarousel" class="carousel carousel-dark slide carousel-fade row justify-content-center align-content-center align-items-center">
            <div class="carousel-indicators">
                <button type="button" data-bs-target="#qualityQueriesCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                <button type="button" data-bs-target="#qualityQueriesCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
                <button type="button" data-bs-target="#qualityQueriesCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
                <button type="button" data-bs-target="#qualityQueriesCarousel" data-bs-slide-to="3" aria-label="Slide 4"></button>
                <button type="button" data-bs-target="#qualityQueriesCarousel" data-bs-slide-to="4" aria-label="Slide 5"></button>
            </div>
            <div class="carousel-inner">
                <div class="carousel-item active qualityQueriesCarouselItem d-flex row g-0 d-grid">
                    <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-5 col-xxl-3">
                        <div class="text-center p-2 jumbotron" style="background: rgba(0, 0, 0, 0.7);">
                            <h1>Python with Flask and SQLAlchemy</h1>
                        </div>
                        <p class='p-2 py-3 bgc'>
                            Your SQL journey begins here.
                        </p>
                    </div>
                    <div class='col-12 col-sm-12 col-md-12 col-lg-12 col-xl-7 col-xxl-9'>
                        <img src="{{ url_for('information.static', filename='img/F12EBB76B5C0C26F467EC95A23CA1AB888292FF08A72A206D1B10EB009E856A6.webp')}}" class="d-block w-100" alt="...">
                    </div>
                </div>
                <div class="carousel-item qualityQueriesCarouselItem d-flex row g-0 d-grid">
                    <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-5 col-xxl-3">
                        <div class="text-center p-2 jumbotron" style="background: rgba(0, 0, 0, 0.7);">
                            <h1>Why Should You Care?</h1>
                        </div>
                        <p class='p-2 py-3 bgc'>
                            - SQL is a language for working with data in databases.{{ spacer(1) }}
                            - Tells the database what data you want, not how to get it.{{ spacer(1) }}
                            - Uses tables to store data. Tables have rows and columns, like a spreadsheet.{{ spacer(1) }}
                            - Has many versions, but they all follow a standard.{{ spacer(1) }}
                            - The language is used in various industries for handling vast amounts of data.{{ spacer(1) }}
                            - Helps people store and retrieve important information.{{ spacer(1) }}
                            - Ensures that your data is well-organized and easily accessible.{{ spacer(1) }}
                        </p>
                    </div>
                    <div class='col-12 col-sm-12 col-md-12 col-lg-12 col-xl-7 col-xxl-9'>
                        <img src="{{ url_for('information.static', filename='img/46F55F71F019B6D3DA7AC3CD413627002FA3324E3417DB4DD449790DFBA52DB0.webp')}}" class="d-block w-100" alt="...">
                    </div>
                </div>
                <div class="carousel-item qualityQueriesCarouselItem d-flex row g-0 d-grid">
                    <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-5 col-xxl-3">
                        <div class="text-center p-2 rounded-startmx-auto jumbotron" style="background: rgba(0, 0, 0, 0.7);">
                            <h1>Why Bother with SQL?</h1>
                        </div>
                        <p class='p-2 py-3 bgc'>
                            - SQL is the language of data.{{ spacer(1) }}
                            - SQL is everywhere and essential for many aspects of our lives.{{ spacer(1) }}
                            - SQL empowers us to discover insights and knowledge from data.{{ spacer(1) }}
                            - SQL is a universal and transferable skill.{{ spacer(1) }}
                            - SQL can be applied to various domains and industries.{{ spacer(1) }}
                        </p>
                    </div>
                    <div class='col-12 col-sm-12 col-md-12 col-lg-12 col-xl-7 col-xxl-9'>
                        <img src="{{ url_for('information.static', filename='img/50C44B7E641BFC56C7FC9A48A5A9480AF39AC94133E0120B853693EEC3436626.webp')}}" class="d-block w-100" alt="...">
                    </div>
                </div>
                <div class="carousel-item qualityQueriesCarouselItem d-flex row g-0 d-grid">
                    <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-5 col-xxl-3">
                        <div class="text-center p-2 jumbotron" style="background: rgba(0, 0, 0, 0.7);">
                            <h1>Who uses SQL?</h1>
                        </div>
                        <div class="text-start rounded-bottom p-2 mx-auto jumbotron">
                            <div data-bs-theme='dark' class="accordion" id="accordionSQLExampleUses">
                                <div class="accordion-item">
                                    <h2 class="accordion-header">
                                        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseaccordionSQLExampleUsesOne" aria-expanded="true" aria-controls="collapseaccordionSQLExampleUsesOne">
                                            <i><b>Marketing</b></i>
                                        </button>
                                    </h2>
                                    <div id="collapseaccordionSQLExampleUsesOne" class="accordion-collapse collapse show" data-bs-parent="#accordionSQLExampleUses">
                                        <div class="accordion-body">
                                            Helps analyze customer behavior, segment customers, track campaigns, and optimize conversions.
                                        </div>
                                    </div>
                                </div>
                                <div class="accordion-item">
                                    <h2 class="accordion-header">
                                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseaccordionSQLExampleUsesTwo" aria-expanded="false" aria-controls="collapseaccordionSQLExampleUsesTwo">
                                            <i><b>Backend Development</b></i>
                                        </button>
                                    </h2>
                                    <div id="collapseaccordionSQLExampleUsesTwo" class="accordion-collapse collapse" data-bs-parent="#accordionSQLExampleUses">
                                        <div class="accordion-body">
                                            Helps manipulate data for web applications.
                                        </div>
                                    </div>
                                </div>
                                <div class="accordion-item">
                                    <h2 class="accordion-header">
                                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseaccordionSQLExampleUsesThree" aria-expanded="false" aria-controls="collapseaccordionSQLExampleUsesThree">
                                            <i><b>Accounting</b></i>
                                        </button>
                                    </h2>
                                    <div id="collapseaccordionSQLExampleUsesThree" class="accordion-collapse collapse" data-bs-parent="#accordionSQLExampleUses">
                                        <div class="accordion-body">
                                            Helps store, retrieve, and analyze financial data, as well as generate reports and invoices.
                                        </div>
                                    </div>
                                </div>
                                <div class="accordion-item">
                                    <h2 class="accordion-header">
                                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseaccordionSQLExampleUsesFour" aria-expanded="false" aria-controls="collapseaccordionSQLExampleUsesFour">
                                            <i><b>Data Science</b></i>
                                        </button>
                                    </h2>
                                    <div id="collapseaccordionSQLExampleUsesFour" class="accordion-collapse collapse" data-bs-parent="#accordionSQLExampleUses">
                                        <div class="accordion-body">
                                            Helps accessing, cleaning, and exploring data, as well as perform statistical analysis and machine learning.
                                        </div>
                                    </div>
                                </div>
                                <div class="accordion-item">
                                    <h2 class="accordion-header">
                                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseaccordionSQLExampleUsesFive" aria-expanded="false" aria-controls="collapseaccordionSQLExampleUsesFive">
                                            <i><b>Data Analysis</b></i>
                                        </button>
                                    </h2>
                                    <div id="collapseaccordionSQLExampleUsesFive" class="accordion-collapse collapse" data-bs-parent="#accordionSQLExampleUses">
                                        <div class="accordion-body">
                                            Help query, transform, and visualize data, as well as generate insights and recommendations.
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class='col-12 col-sm-12 col-md-12 col-lg-12 col-xl-7 col-xxl-9'>
                        <img src="{{ url_for('information.static', filename='img/B1C24B8980EB583C02AD3DEF9CE0FBDB8533CE961890DA39A09AA49DBB160A33.webp')}}" class="d-block w-100" alt="...">
                    </div>
                </div>
                <div class="carousel-item qualityQueriesCarouselItem d-flex row g-0 d-grid">
                    <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-5 col-xxl-3">
                        <div class="text-center p-2 jumbotron" style="background: rgba(0, 0, 0, 0.7);">
                            <h1>Conclusion</h1>
                        </div>
                        <p class='p-2 py-3 bgc'>
                            - MySQL stands as a cornerstone in the world of relational databases.{{ spacer(1) }}
                            - SQL offers a lot of very good job opportunities.{{ spacer(1) }}
                            - SQL is an integral part of web development For Backend developers.{{ spacer(1) }}
                            - SQL is partly responsible for determining the speed of an application.{{ spacer(1) }}
                            - SQL opens doors to other job opportunities like Data Analysts, Data Administrators.{{ spacer(2) }}

                            Thank you for joining for our introduction for MySQL.
                            We hope we made Our introduction Very Simple and consise
                            And We hope our video gave you a brief introduction to MYSQL
                        </p>
                    </div>
                    <div class='col-12 col-sm-12 col-md-12 col-lg-12 col-xl-7 col-xxl-9'>
                        <img src="{{ url_for('information.static', filename='img/908CDBD7049C947441F99DD19D55A0A6FC3D68155FC579D00F223F56B0E19752.webp')}}" class="d-block w-100" alt="...">
                    </div>
                </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#qualityQueriesCarousel" data-bs-slide="prev">
                <span aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#qualityQueriesCarousel" data-bs-slide="next">
                <span  aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
    </div>
    <div id="qualityQueries" class="rounded jumbotron container-fluid p-2 my-3 jbtron"></div>
    <script src="{{ url_for('information.static', filename='js/_presentation.js')}}"></script>
{% endblock %}

alchemy/information/templates/versions.html
{% extends '_base.html' %}
{% block title %}Modules{% endblock %}
{% block content %}
    <div class="container-fluid jumbotron rounded p-2 my-3 text-center jbtron">
        <div class="jumbotron rounded bgc p-3 my-2">
            <div class="jumbotron rounded fgc px-4 pb-4 pt-4 mt-1 mb-0">
                <h3 class='my-4'>Python {{ python_version }}</h3>
                <h5 class='my-4'>Python {{ python_version_info }}</h5>
            </div>
            {{ errors() }}
            <div class="jumbotron fgc rounded pb-4 px-4 pt-5 mb-1 mt-4">
                <form method="POST">
                    {{ form.hidden_tag() }}
                    <div class="input-group input-group-sm input-group-smaller">
                        <div class="input-group-prepend">
                            <span>{{ form.submit(class="btn formInputPrefix btn-primary btn-block mb-4", id="regex_n_redirect")}}</span>
                        </div>
                        {{ form.search(class="inptbx rounded-end form-control", placeholder="search for or filter through modules", id="module_regex_searching") }}
                        <input id="get_more_info_id" name="get_more_info" type="hidden" value="{{ pip3_modules['load'] }}">
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="jumbotron rounded container-fluid jbtron p-2 my-2">
        <div class="jumbotron rounded container-fluid my-2 p-2 bgc {{ 'row' if not pip3_modules['TypeNone'] }}">
            {% if pip3_modules['TypeNone'] %}
                <div class="jumbotron fgc rounded p-3">
                    <h5 class="text-center"><b>No modules were found.</b></h5>
                </div>
            {% else %}
                {% for module in pip3_modules['names_n_versions'] %}
                    {% if module['name'] in pip3_modules['names'] %}
                        <div class="col-sm-4 my-3">
                            <div class="card">
                                <div class="card-body fgc">
                                    <h5 class="card-title text-light"><b>Module:</b> {{ module['name'] }}</h5>
                                    <p class="card-text text-light"><b>Version:</b> {{ module['version'] }}</p>
                                    <button class="btn my-1 col-12 text-center btn-secondary" id="{{ module['name'] }}" onclick="getMoreInfo('{{ module['name'] }}')">More Info</button>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
            {% endif %}
            <script>
                document.getElementById('get_more_info').value = 'None'
            </script>
        </div>
    </div>
    <script src="{{ url_for('information.static', filename='js/_versions.js')}}"></script>
{% endblock %}